version: '3'
services:
  # ----------------------------------------------------------------
  # REDIS SOCKET.IO
  # ----------------------------------------------------------------
  stock_redis_1:
    image: bitnami/redis:latest
    container_name: stock_redis_1
    ports:
      - 6370:6379
    restart: always
    environment:
      - TZ=Asia/Seoul
      - REDIS_PASSWORD=stock

  # ----------------------------------------------------------------
  # PSQL DATABASE
  # ----------------------------------------------------------------
  # stock_pg_1:
  #   image: bitnami/postgresql:latest
  #   container_name: stock_pg_1
  #   ports:
  #     - 5401:5432
  #   volumes:
  #     - /opt/docker/stock_be/services/stock_pg_1:/stock_pg_1_data
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: always
  #   environment:
  #     - POSTGRESQL_PASSWORD=stock
  #     - POSTGRESQL_DATABASE=stock
  #     - POSTGRESQL_REPLICATION_MODE=master
  #     - POSTGRESQL_REPLICATION_USER=stock
  #     - POSTGRESQL_REPLICATION_PASSWORD=stock